version: '3.9'

services:
  rosbridge:
    build:
      context: ./
    container_name: rosbridge_container
    # network_mode: host # Share the host network for easier access
    ports:
      - "9090:9090"
      - "8443:8443"
      
    restart: unless-stopped
    # environment:
    #   - ROS_DOMAIN_ID=0  # Adjust this if you're using a specific ROS domain ID
    #   - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./rosbridge:/root/rosbridge_launch
    command: ["/root/rosbridge_launch/start.sh"]
