@startuml Navigation State Machine
hide empty description

[*] -right-> Init
Init -right-> LongRange
LongRange -up-> LongRange : notComplete
LongRange -down-> Error : error
Error -down-> LR_Recovery
LR_Recovery --> LR_Recovery : notComplete
LR_Recovery --> Error : error
LR_Recovery --> LongRange : success
LongRange -right-> ShortRange : success
ShortRange --> ShortRange : notComplete
ShortRange -left-> LongRange : error
ShortRange --> WaypointSuccess : success
WaypointSuccess --> WaypointSuccess : waiting
WaypointSuccess -up-> LongRange : notWaiting

@enduml